name: Frontend Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'iaac/**'                               # Trigger only when infra files change
      - '.github/workflows/infrastructure.yml'
  workflow_dispatch:                          # Allow manual triggering from GitHub UI

jobs:
  plan-frontend-infra:
    name: Plan Frontend Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iaac

    steps:
      - name: Checkout
        uses: actions/checkout@v3           # Pulls repo code into runner

      - name: List files in iaac folder # Skip in Production 
        run: ls -la
        
      - name: Mask GitHub Token
        run: echo "::add-mask::${{ secrets.GITHUB_TOKEN }}"  # Hide GitHub token in logs

      - name: Mask Azure Subscription ID
        run: echo "::add-mask::${{ secrets.AZURE_SUBSCRIPTION_ID }}"  # Hide sub ID in logs
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TFSTATE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2       # Installs Terraform CLI

      - name: Terraform Init (with backend config)   # Prepares Terraform backend
        run: |
          terraform init \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=zchtfstatestorageacc" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=frontend.tfstate"

      - name: Prepare log file
        run: touch terraform.log

      - name: Terraform Plan
        working-directory: iaac 

        #env: Uncomment for debug
        #  TF_LOG: DEBUG
        #  TF_LOG_PATH: terraform.log
        run: terraform plan -var-file="terraform.tfvars" -out=plan.tfplan

      #- name: Show Terraform debug log
      #  run: cat terraform.log

      #- name: List Terraform plan file if exists
      #  run: ls -la plan.tfplan || echo "plan.tfplan does not exist"

      - name: Upload Terraform Plan      # Saves the plan for the apply stage
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: iaac/plan.tfplan

  apply-frontend-infra:
    name: Apply Frontend Infrastructure
    runs-on: ubuntu-latest
    needs: plan-frontend-infra      # Waits for planning job

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mask Azure Subscription ID
        run: echo "::add-mask::${{ secrets.AZURE_SUBSCRIPTION_ID }}"  # Hide sub ID

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    # Auth to Azure with SP

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2      #   Ensure Terraform is available
      
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4   # Retrieve saved plan file
        with:
          name: terraform-plan
          path: iaac


      - name: Terraform Init (with backend config)   # Needed again in apply stage
        working-directory: iaac
        run: |
          terraform init \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=zchtfstatestorageacc" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=frontend.tfstate"

      - name: Terraform Apply
        working-directory: iaac
        run: terraform apply -no-color -auto-approve plan.tfplan
        # -no-color keeps logs clean
        # -auto-approve skips confirmation prompts

      - name: Output Details
        working-directory: iaac
        run: |
          echo "### Frontend Infrastructure Deployed! 🚀" >> $GITHUB_STEP_SUMMARY
          echo "- **Frontend URL**: $(terraform output -raw static_website_url)" >> $GITHUB_STEP_SUMMARY
